name: Execute PowerShell Script

on:
  push:
    branches:
      - main  # Adjust branch name if needed

jobs:
  build:
    runs-on: windows-latest  # GitHub Actions Windows runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Execute PowerShell script
      shell: pwsh
      run: |
        echo ${{ secrets.ORG_NAME }}
        .\explorer.ps1

      env:
        orgName: ${{ secrets.ORG_NAME }}  # Define orgName secret in repository settings > Secrets
        token: ${{ secrets.TOKEN }}        # Define token secret in repository settings > Secrets
