name: Execute PowerShell Script

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Execute PowerShell script
      shell: pwsh
      env:
        orgName: ${{ secrets.ORG_NAME }}
        token: ${{ secrets.TOKEN }}
      run: |
        .\explorer.ps1 -type ${{ matrix.type }}

    - name: Explorer workspaces
      uses: actions/upload-artifact@v4
      with:
        name: workspacedetails
        path: output.csv

    # Define the types to run the job for each specified type
    strategy:
      matrix:
        type: [workspaces, providers, modules]
