name: Execute PowerShell Script

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Execute PowerShell script
      shell: pwsh
      env:
        orgName: ${{ secrets.ORG_NAME }}
        token: ${{ secrets.TOKEN }}
      run: |
        Invoke-WebRequest -Uri "https://app.terraform.io/api/v2/organizations/$orgName/explorer?type=providers" -Headers @{ "Authorization" = "Bearer $token" }
