name: Execute PowerShell Script

on:
  push:
    branches:
      - main  # Adjust branch name if needed

jobs:
  build:
    runs-on: windows-latest  # GitHub Actions Windows runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Execute PowerShell script
      shell: pwsh
      run: |
        .\explorer.ps1

      env:
        orgName: "wpp-cloudhub-dev"
        token: "P2vnQg0sB1nNKg.atlasv1.A7kByyMQzM6YRWismCOlH9nEbAEK2fU4KhDNCvwS2qdqqgP1pzQRGYH8pC7ioQ4Cb60"      # Define token secret in repository settings > Secrets
